-- PART 3 HW --
DROP TABLE ENROLLMENT CASCADE CONSTRAINTS;
DROP TABLE SECTION CASCADE CONSTRAINTS;

CREATE TABLE SECTION(
 SectionID 	CHAR(5),
 Course	VARCHAR2(7),
 Students	NUMBER DEFAULT 0,
 CONSTRAINT PK_SECTION 
		PRIMARY KEY (SectionID)
);

CREATE TABLE ENROLLMENT(
 SectionID	CHAR(5),
 StudentID	CHAR(7),
 CONSTRAINT PK_ENROLLMENT 
		PRIMARY KEY (SectionID, StudentID),
 CONSTRAINT FK_ENROLLMENT_SECTION 
		FOREIGN KEY (SectionID)
		REFERENCES SECTION (SectionID)
);

INSERT INTO SECTION (SectionID, Course) VALUES ( '12345', 'CSC 355' );
INSERT INTO SECTION (SectionID, Course) VALUES ( '22109', 'CSC 309' );
INSERT INTO SECTION (SectionID, Course) VALUES ( '99113', 'CSC 300' );
INSERT INTO SECTION (SectionID, Course) VALUES ( '99114', 'CSC 300' );
COMMIT;
SELECT * FROM SECTION;

--- Creating Trigger A --
SET SERVEROUTPUT ON;

CREATE OR REPLACE TRIGGER studentNum
BEFORE INSERT ON ENROLLMENT
FOR EACH ROW
DECLARE
    numStudent NUMBER;
BEGIN
    SELECT COUNT(*) INTO numStudent
    FROM ENROLLMENT
    WHERE SectionID = :new.SectionID;
    numStudent := numStudent + 1;
    
    If numStudent > 5 THEN 
        raise_application_error(-20102, 'Canont insert more students, section is full!');
    ELSIF numStudent <= 5 THEN
        UPDATE SECTION SET SECTION.Students = numStudent
        WHERE SECTION.SectionID = :new.SectionID;
    END IF;
END;
/

-- Testing Trigger A --
INSERT INTO ENROLLMENT VALUES ('12345', '1234567');
INSERT INTO ENROLLMENT VALUES ('12345', '2234567');
INSERT INTO ENROLLMENT VALUES ('12345', '3234567');
INSERT INTO ENROLLMENT VALUES ('12345', '4234567');
INSERT INTO ENROLLMENT VALUES ('12345', '5234567');
INSERT INTO ENROLLMENT VALUES ('12345', '6234567');
SELECT * FROM Section;
SELECT * FROM Enrollment;

-- Creating B Trigger --
CREATE OR REPLACE TRIGGER delStudent
BEFORE DELETE ON ENROLLMENT
FOR EACH ROW
BEGIN
    UPDATE SECTION
    SET Students = Students -1
    WHERE SectionID = :old.SectionID;
END;


-- TESTING B TRIGGER --
DELETE FROM ENROLLMENT WHERE StudentID = '1234567';
SELECT * FROM Section;
SELECT * FROM Enrollment;
